name: sound_box
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.2.2
  audio_session: ^0.2.2
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dart_code_metrics: ^5.7.6

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/sounds/variants/
